name: zerror
description: A Flutter project for zerror.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  latext: ^0.5.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^4.12.0
  flutter_local_notifications: ^21.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0  # 🌟 1. 引入启动页生成工具

flutter:
  uses-material-design: true

  # 🌟 新增的图片资源注册区域
  # 注意：assets 前面有 2 个空格，- 号前面有 4 个空格
  assets:
    - assets/images/splash_bg.png
    - assets/images/auth_bg.png # 🌟 新增这一行
    - assets/images/logo.png
    - assets/images/background_dark.png
    - assets/images/background_light.png
    - assets/images/logo.webp
    - assets/images/splash_bg1.png
    - assets/images/splash_bg2.png
    - assets/images/splash_bg3.png
    - assets/images/splash_bg4.png
    - assets/images/splash_bg5.png
    - assets/images/splash_bg6.png

# 🌟 2. 在文件最底部，贴上这段专属配置（注意不要缩进，顶格写）
flutter_native_splash:
  color: "#1A2421" # 强制底色为你森林背景的深松木绿
  # Android 12+ 专属霸道配置，强制覆盖它的默认行为
  android_12:
    color: "#1A2421"
