name: zerror
description: A Flutter project for zerror.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  latext: ^0.5.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^4.12.0
  flutter_local_notifications: ^21.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0  # 启动页生成工具

flutter:
  uses-material-design: true

  # 图片资源注册区域
  # 注意：assets 前面有 2 个空格，- 号前面有 4 个空格
  assets:
    - assets/images/splash_bg.png
    - assets/images/auth_bg.png
    - assets/images/logo.png
    - assets/images/background_dark.png
    - assets/images/background_light.png
    - assets/images/logo.webp
    - assets/images/flat_study_illustration.png
    - assets/images/ai_chat_illustration.png
    - assets/images/ai_slime_orb.png
    - assets/images/ai_orb_shadow.png
    - assets/images/empty_study_illustration.png
    - assets/images/flat_chat_icon.png
    - assets/images/splash_bg1.png
    - assets/images/splash_bg2.png
    - assets/images/splash_bg3.png
    - assets/images/splash_bg4.png
    - assets/images/splash_bg5.png
    - assets/images/splash_bg6.png

# 启动页专属配置，保持顶格。
flutter_native_splash:
  color: "#1A2421"
  # Android 12+ 专属配置，覆盖默认启动页背景。
  android_12:
    color: "#1A2421"
